---
services:
  goblog:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      GOBLOG_CONFIG_PATH: /goblog/config
    volumes:
      - ./goblog.json:/goblog/config:ro
      - ../content:/goblog/content:ro
    ports:
      - 8080:8080
